### PR TITLE
fix: allow negative at start of entry

### PR DESCRIPTION
**Pull request by iamkevla**
allow the entry of negative at start instead of as is currently after first entering numbers

### CODE REVIEW

**Comment by apansky** [comment]
Any chance of this being merged? Would solve my problem too..

**Comment by arg23** [comment]
Any chance of this being merged?

**Comment by JuanmaOrtizSisamon** [comment]
This is a good solution for me too :)

**Review by noelmccrory — APPROVED** [review]

**Comment by leonandroid** [comment]
Hi guys, any chance this can be approved? It will solve a problem we are facing as well.

**Review by leonandroid — APPROVED** [review]
Looks good, and looking forward for this to be released.

**Comment by antonioclaudioneiva** [comment]
This is a good solution for me too!

**Comment by KatyaBaranovskaya** [comment]
@nbfontana Could you answer if you plan to merge?

**Comment by ElChouaib** [comment]
SOS !! Please merge this pull request

**Comment by ElChouaib** [comment]
any intermediary solutions ??

**Comment by ArturQuirino** [comment]
Please someone merge this PR. It will solve a problem we are facing.

**Comment by nbfontana** [comment]
This is merged and I'm running some tests (it seems that this won't work with the natural type, only with the financial) I'm updating the natural type so that when we use the negative value as the first keystroke, we select all the remaining numbers and allow directly typing and changing the values...

Will release a 3.0 later today (cause I don't have too much time to test other edge cases and don't want to break current users of 2.*)

Sorry about the delay on this project (new jobs, new stuff on life, you get your mind on other priorities)

**Pull request merged**
