### PR TITLE
Updated Angular

### PR DESCRIPTION
**Pull request by lucas-sesti**
I updated the version of Angular to v10, and fixed ModuleWithProviders, because now, is necessary add a type.

### CODE REVIEW

**Comment by vtregner** [comment]
Urgently needed this pull request, lib doesn't work with angular 10

**Comment by lucas-sesti** [comment]
Yeah... the ngx-currency dont see my pull request, i don't know why... i need urgently too

**Comment by thiendang18** [comment]
@nbfontana please check. Thanks

**Comment by nbfontana** [comment]
Looking into it guys, sorry about the delay

**Pull request merged**
