### PR TITLE
Migrate to Angular 16

### PR DESCRIPTION
**Pull request by ArtemDintecom**
**Improved:**
* Make a standalone directive and drop of the module
* Renamed `CurrencyMaskConfig` to `NgxCurrencyConfig`
* Renamed `CurrencyMaskInputMode` to `NgxCurrencyInputMode`
* Renamed `CURRENCY_MASK_CONFIG` to `NGX_CURRENCY_CONFIG`
* Renamed `CurrencyMaskDirective` to `NgxCurrencyDirective`
* Now you can partially override the global configuration
* Stronger project typing, drop of `any`
* Changed project structure to build via Angular CLI
* Updated README to use `provideEnvironmentNgxCurrency` instead of `forRoot`

**Broke/lost:**
* Travis-CI 
* standard-version (it is outdated and I still don't know what to migrate it to)
* scripts for publishing a new version
* May be something else...

**Closes** #152, #153, #155, #167

### CODE REVIEW

**Comment by ThemisCol** [comment]
Excellent contribution.

The test (should return null because the nullable parameterization is true) have error.

An argument of type "number" cannot be assigned to parameter of type "Expected<ArrayLike<number>> | ArrayContaining<number>".

**Comment by ArtemDintecom** [comment]
@ThemisCol I swapped expected and actual values. But I did not understand where there is a mismatch of types? Could you describe in a little more detail?

**Comment by pumano** [comment]
any news on this? Library become totally not working since 16 angular

**Comment by ArtemDintecom** [comment]
@pumano Looks like we'll have to wait a long time for the owner of the library. But I don’t really want to upload my project to npm and change the package name throughout the code. So I just added this to package.json:
```json
  "dependencies": {
    ...
    "ngx-currency": "https://github.com/dintecom/ngx-currency-dist#v15.0.0-2",
    ...
  }
```
You can do the same or build the package yourself, fortunately now it's easy to do, with one command `npm run build:lib`

**Comment by TiLopes** [comment]
How would I import the module?

**Comment by TiLopes** [comment]
With this changes how would I use the library now? I have never used directives.

**Review by danielehrhardt — APPROVED** [review]

**Comment by steflen-kxl** [comment]
Would love to see this soon

**Comment by tortuc** [comment]
When will it be merged?
I stopped using this package due to same error, It doesn't work in Angular 16.

**Comment by gamoreli** [comment]
Hey guys, could you please merge it?

**Comment by selangley-wa** [comment]
Merge this?
@nbfontana

**Comment by nbfontana** [comment]
Hey devs,

First of all, thank you @ArtemDintecom!

I'm really late to this one and it is a deal breaker for lots of projects for sure. 

I'm not as close to Angular as I used to be and might not be the best person to review, refactor or search for possible nuances within all of the changes in this PR. Although **I'll work on releasing this as a new major version today**, do some smoke testing.

The GitHub Notifications are a bit overwhelming and when mixed with work stuff it gets hard to even circle back to a PR that a saved on my todo list months ago 🫠

I could easily add a bunch of you that are using the lib as collaborators, secure master, and request a minimal number of CR approvals so it's more spread and I don't leave it blocked... Will then work on improving the release so it's also not blocked but still secure and solid.

Thoughts?

**Comment by ArtemDintecom** [comment]
@nbfontana Thank you for releasing a new version!
You want one of us to additionally review future pull requests, and you will pay more attention to releases of new versions, right? You can add me to the collaborators, but I think this is not necessary. I can simply subscribe to any pull requests changes in this repository and review them when I have free time.

**Comment by nbfontana** [comment]
@ArtemDintecom sounds good to me!

I'll try to update my notification warnings to get e-mails from this repo. Since I don't get e-mails from anything else on Github that should work as a good reminder 😅

Also need to revisit a few things since some dev things stopped working on 4.0.0, like auto-generating versions/changelogs etc

**Pull request merged**
