### PR TITLE
Migrate to Angular 17

### LINKED ISSUE #183: 4.0.0 changelog
Hi,

I see a 4.0.0 version in https://www.npmjs.com/package/ngx-currency?activeTab=versions but nothin in the repo and the changelog.

What are the changes ?

Thx !

### PR DESCRIPTION
**Pull request by ArtemDintecom**
In addition to the new Angular, I tried to return the standard-version, replacing it with `commit-and-tag-version`.
For this to work you will need to manually create the `v4.0.0` tag on commit 1b561bcd004fe090e603cb601ce6cad9267f119d.
Then before the new version is released it will be possible to run `npm run release -- --release-as major`.
It was great to sync the major version of ngx-currency with the Angular version and release version 17 instead of 5. More and more libraries are coming to this, and this is very convenient for developers because libraries usually do not declare backward compatibility.

Closes #183, #184

### CODE REVIEW

**Comment by mtosic** [comment]
Hi @ArtemDintecom , is there any way to use your fork from npm before it's merged?
I've tried `npm install git+https://github.com/dintecom/ngx-currency#upgrade`, but on build process I'm getting errors on importing `import { NgxCurrencyInputMode, provideEnvironmentNgxCurrency } from 'ngx-currency';` (module can't be found).

Guess I need to build library myself (from fork), but not sure how to do it.

**Comment by ArtemDintecom** [comment]
@mtosic Yes, you can use it by adding this to `package.json`:
```json
  "dependencies": {
    ...
    "ngx-currency": "https://github.com/dintecom/ngx-currency-dist#v17.0.0-1",
    ...
  }
```
NPM doesn't always understand these links well, so you may have to clean out the `node_modules` folder and install the packages again with `npm install`.

**Comment by mtosic** [comment]
Thx, that worked!

**Comment by vtregner-cen29414** [comment]
Can you merge and release new version pls?

**Pull request merged**
